name: ts_studio
description: Teivrim Sound Studio (TS Studio) - мобильная музыкальная студия для Android
publish_to: 'none'
version: 0.9.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  audioplayers: ^6.1.0
  record: ^5.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/samples/
